classDiagram
    class Apprenant {
        +id: int
        +nom: string
        +email: string
        +progression: EtatProgression
    }

    class Autoformation {
        +id: int
        +titre: string
        +description : string
        +progressionGlobale: EtatProgression
    }

    class Tuto {
        +id: int
        +titre: string
        +contenu: string
        +progression: EtatProgression
    }

    class Formation {
        +id: int
        +titre: string
        +description: string
    }

    class Realisation {
        +id: int
        +date: Date
        +status: string
    }

    class EtatProgression {
        <<enumeration>>
        TO_DO
        IN_PROGRESS
        DONE
    }

    %% Relationships
    Apprenant "1" -- "*" Autoformation : suit
    Formation "1" -- "*" Tuto : contient
    Formation "1" -- "*" Autoformation : contient
    Autoformation "1" -- "*" Realisation : suit
    Tuto "1" -- "1" EtatProgression : suit
    Tuto "1" -- "1" Realisation : estLiéeÀ
