mindmap
  root((Apprenant))
    Dit
      Dit["Je veux comprendre clairement ma progression."]
      Dit["Je me sens frustré(e) lorsque je ne sais pas où je rencontre des difficultés."]
      Dit["J'ai besoin d'aide lorsque je ne peux pas terminer les tutoriels ou projets à temps."]
    Fait
      Fait["Je passe du temps à revoir mes propres progrès."]
      Fait["Je me sens anxieux/-se à l'idée de prendre du retard."]
      Fait["Parfois, je suis ma progression de façon informelle, mais ce n'est pas organisé."]
    Besoin
      Besoin["Une vue détaillée de ma progression globale."]
      Besoin["Des retours sur mes performances et des axes d'amélioration."]
      Besoin["Des outils ou un soutien pour surmonter les défis dans les tutoriels ou projets."]
